dist: trusty
sudo: false

env:
  global:
    - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom

rvm:
  - 2.2
  - 2.3
  - 2.4
  - jruby-9.1.15.0
  - 2.5

matrix:
  allow_failures:
    - rvm: 2.5

before_install:
  - gem update bundler